# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41dfee141d2779c7ba9f697e0f78835e424f131bff7b320ad4549f789b6edb8119103dd441b6a610918151a8d88a41cbb4c0abcaa2920b2e488d96ee17935632

test:
  secret_key_base: f3b0b4f37e2913363d86fc7f15e6b23058f89da46c936c2b0f94b02ae3fca041160fc911c191e87111c5e3e9b6f6de57db7f95388ff451bf83d7b3f266272186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
